siteName: Mathigon
description: A interactive textbook
domain: mathigon.org

privacyURL: /policies
banner: (c) Mathigon
locales: [en, ar, cn, de, es, fr, hi, hr, it, ja, pt, ro, ru, sv, tr, vi]

search:
  enabled: false

footer:
  rows:
    - links:
        - title: GitHub
          url: https://github.com/mathigon/textbooks
        - title: Live Website
          url: https://mathigon.org/courses
  copyright: Â© Mathigon, 2021

social:
  facebook: {}
  twitter: {}

courses:
  showLocked: true
  revealAll: false
  audio: false

tutor:
  enabled: true
